image: python:latest

.before_test_template:
  before_script:
    - echo "Preparing python for tests..."
    - python setup.py

stages:
  - Code tests
  - Development image tests
  - Production image build tests

pylint:
  stage: Code tests
  extends: .before_test_template
  tags:
    - common
  script:
    - echo "Checking codestyle..."
    - python static_analyze

pytest:
  stage: Code tests
  extends: .before_test_template
  tags:
    - common
  script:
    - echo "Starting tests..."
    - python -m pytest tests -rfs --cov=src
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/


test_image:
  image: docker:20.10.24
  #only:
  #  - main
  #  - merge_requests
  tags:
    - dind
  needs:
    - pytest
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.24-dind
  stage: Development image tests
  script:
    - docker info
    - echo "Starting building image..."
    - docker build --target development -t my-image .
    - echo "Starting test image..."
    - docker run --name my-container -td my-image bash
    - docker exec -w /home/user/project my-container  python -m pytest --cov src tests
    - docker stop my-container

build_production_image:
  image: docker:20.10.24
  #only:
  #  - main
  #  - merge_requests
  tags:
    - dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.24-dind
  stage: Production image build tests
  script:
    - docker info
    - echo "Starting building image..."
    - docker build -t my-image .
    - echo "Starting test image..."
    - docker run --name my-container my-image bash